app:
  name: fhir-to-server
  log-level: info

kafka:
  bootstrap-servers: localhost:9092
  security-protocol: ssl
  ssl:
    ca-location: /app/cert/kafka-ca.pem
    certificate-location: /app/cert/app-cert.pem
    key-location: /app/cert/app-key.pem
    key-password:
  input-topics:

fhir:
  server:
    base-url: http://localhost:8080/fhir
    auth:
      user:
      password:
  retry:
    count: 10
    timeout: 10
    wait: 5
    max-wait: 20
  filter:
    date:
      value: # example: "2020-06-15"
      comparator: # example: ">="
