version: "3.7"

services:
  lab-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b localhost:9092 -K: -t lab-fhir -P -l /data/lab-data.ndjson"
    volumes:
      - ./lab-data.ndjson:/data/lab-data.ndjson:ro
    network_mode: host

  person-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b localhost:9092 -K: -t person-fhir -P -l /data/person-data.ndjson"
    volumes:
      - ./person-data.ndjson:/data/person-data.ndjson:ro
    network_mode: host
